branch-defaults:
  master:
    environment: iman
    group_suffix: null
global:
  application_name: portfolio
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
