branch-defaults:
  master:
    environment: 1Cademy
global:
  application_name: 1Cademy
  default_ec2_keyname: 1Cademy
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
